name: Build

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Android
          path: build/app/outputs/flutter-apk/*.apk

  
